<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-primitive-icon</name>
   <tag></tag>
   <elementGuidId>26f01b00-fd67-4743-ac7b-d96f3cd48dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/div/div/div/div/div/ul/li[6]/div/lightning-button/button/lightning-primitive-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;a3X5e000000Vc8QEAS&quot;] > lightning-primitive-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-primitive-icon</value>
      <webElementGuid>f4a8c03f-b5c9-44c2-902d-48643a0af736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/siqic-qr_-list-page-lwc[1]/div[@class=&quot;row&quot;]/div[@class=&quot;slds-grid slds-p-around--medium&quot;]/div[1]/div[@class=&quot;vertical-scroll&quot;]/div[1]/div[@class=&quot;slds-tree_container&quot;]/ul[@class=&quot;slds-tree&quot;]/li[6]/div[@class=&quot;slds-tree__item&quot;]/lightning-button[@class=&quot;slds-tree__item-label slds-truncate&quot;]/button[@class=&quot;slds-button&quot;]/lightning-primitive-icon[1]</value>
      <webElementGuid>4acc6985-a840-4814-805f-216073ab215c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/siqic-qr_-list-page-lwc/div/div/div/div/div/div/ul/li[6]/div/lightning-button/button/lightning-primitive-icon</value>
      <webElementGuid>59c1d383-6ac7-4339-8a16-1b25fc93b1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@#%'])[1]//lightning-primitive-icon[1]</value>
      <webElementGuid>cabafdcd-b46c-41c9-b003-f403f445ab94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@#'])[1]/following::lightning-primitive-icon[1]</value>
      <webElementGuid>855dfcfa-2c8f-420c-b40b-3340204eb850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A IQS TEST'])[1]/preceding::lightning-primitive-icon[1]</value>
      <webElementGuid>1efb4a1e-7f0d-4649-b7d1-4a11854a19f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A4724'])[1]/preceding::lightning-primitive-icon[2]</value>
      <webElementGuid>97894dba-ff0e-4fe0-ae14-0e9d1f1b28dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/lightning-button/button/lightning-primitive-icon</value>
      <webElementGuid>ef778d96-5239-4c61-a7bf-b75cd5bcd2b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
