<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Business Unit</name>
   <tag></tag>
   <elementGuidId>fa4bd579-2557-4898-b08f-9c7b7ee6a7a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'combobox-button-2867' and @type = 'button' and @name = 'businessUnit' and (text() = 'Select Business Unit' or . = 'Select Business Unit')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name=&quot;businessUnit&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-2867</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16b8093f-3905-4c3a-a96a-e12a906a81a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input_faux</value>
      <webElementGuid>1ae672ef-499c-46b5-879e-815b01ee0b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-2867</value>
      <webElementGuid>352f6e2d-2550-4b7f-bfa6-66b2d62ba03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46ef0e3f-012c-4a2c-9588-e0b8fc6a2121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90ca819b-7f2d-4af6-913c-987bb9064a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>d3dc0c72-73a1-4de8-9e36-e60ad21e311a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessUnit</value>
      <webElementGuid>629bd853-9ab0-4002-851d-0e6b1cc1a114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>0c4d85a4-4145-4c99-93c0-07aab5ac1976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Business Unit, Select Business Unit</value>
      <webElementGuid>369db468-7be8-4b9b-8aab-ce49f1c6c172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc2abee2-c1ae-44de-b673-f916810d4494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-2867</value>
      <webElementGuid>fe43cc45-8f54-4d5a-9a3b-07bd6d36272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Business Unit</value>
      <webElementGuid>e59877bc-7ddc-4d18-ba5a-41b765f4cbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-2867&quot;)</value>
      <webElementGuid>dd6fe57d-6578-4edc-8f21-822364f69760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='combobox-button-2867']</value>
      <webElementGuid>65dc51ae-4357-4c66-abab-3933dca5f480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/siqic-qr-new-cycle-creation/div/div[3]/c-qr-h-o-details/div/div/div[2]/lightning-combobox/div/lightning-base-combobox/div/div/button</value>
      <webElementGuid>751a1ccb-6912-4b8b-85ca-b937c3c9ae3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[3]/following::button[1]</value>
      <webElementGuid>3f2ce19b-3100-40ef-9788-0c6722949e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[2]/following::button[1]</value>
      <webElementGuid>b9ed4212-8cd0-4966-be47-0022d8a16bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergybu'])[1]/preceding::button[1]</value>
      <webElementGuid>0fb28042-e644-40be-b1aa-4ad029c4c53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-combobox/div/lightning-base-combobox/div/div/button</value>
      <webElementGuid>bd8e7f80-9483-4c71-bc85-288507e1257a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'combobox-button-2867' and @type = 'button' and @name = 'businessUnit' and (text() = 'Select Business Unit' or . = 'Select Business Unit')]</value>
      <webElementGuid>bd43f709-a1cd-4d7e-a803-7ee0c06bd539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
